### ISSUE TITLE
Registering Photon issues?

### ISSUE THREAD

**Issue by robnolen** [robnolen/devopsday#10]
Put together a foolproof guide to registering a photon.
Completed a short and simple version of connecting the photon.

**Comment by leemikes** [comment]
Check with LeSage. He has a Photon we could not register. (we both tried.. it was odd).  NOTE: He was running Yosemite, and 'photon setup' recognized the Photon over USB, but it never would finish registration.  In contrast, I'm running El Capitan, in which case the Photon WAS NOT visible over USB, but WiFi discovery/activation worked just fine.  NOTE: photon was tied to Verizon MiFi...

**Comment by bshive** [comment]
Here is short registration process:
[Register and Connect to Photon.docx](https://github.com/robnolen/devopsday/files/15403/Register.and.Connect.to.Photon.docx)
